title: Aprendizaje autom√°tico
author: Fernando Crema Garcia
url: "https://ml.ucv.ai"
baseurl: ""
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
favicon_location: "./static/logo.ico"
favicon: yes
#ins_logo: "./static/logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ucvia"
footer_text: "UCVIA | ML | Template basado en Research de Anki Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Principal"
   link: "/"
 - name: "Nota informativa"
   link: "AprendizajeAutomatico-6561.pdf"
 - name: "Contacto"
   link: "contacto"
